spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

resilience4j.circuitbreaker:
  instances:
    orderService:
      slidingWindowSize: 10          # Number of calls to track for failure rate
      failureRateThreshold: 50       # % of failures to trip the circuit
      waitDurationInOpenState: 5000  # Time (ms) to wait before transitioning to Half-Open
      permittedNumberOfCallsInHalfOpenState: 3 # Number of test calls in Half-Open state
      registerHealthIndicator: true   # Expose health details for monitoring
      allowHealthIndicatorToFail: false

management:
  endpoints:
    web:
      exposure:
        include: '*'