spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///C:/Users/User/Documents/config-server-repo/
          timeout: 5
          skip-ssl-validation: true
server:
  port: 8888


#  With VCS-based backends (git, svn), files are checked out or cloned to the local filesystem. By default,
#  they are put in the system temporary directory with a prefix of config-repo-. On linux, for example,
#  it could be /tmp/config-repo-<random-id>. Some operating systems routinely clean out temporary directories.
#  This can lead to unexpected behavior, such as missing properties. To avoid this problem, change the directory
#  that Config Server uses by setting spring.cloud.config.server.git.basedir or spring.cloud.config.server.svn.basedir
#  to a directory that does not reside in the system temp structure.
